source 'https://rubygems.org'

gem 'coffee-script'
gem 'compass'
gem 'jekyll'
gem 'jekyll-assets'
gem 'rake'
gem 'redcarpet'
gem 'breakpoint', '~> 1.x'
gem 'respond-to'
gem 'rubyzip'
gem 'sass'
gem 'uglifier'
gem 'bootstrap-sass', '>= 3.4.0'
gem 'font-awesome-sass'
gem 'webrick'
