source 'https://rubygems.org'

gem 'coffee-script'
gem 'compass'
gem 'jekyll', '>= 3.9.0'
gem 'jekyll-assets', '>= 2.0.0'
gem 'rake', '>= 12.3.3'
gem 'redcarpet', '>= 3.5.1'
gem 'breakpoint', '~> 1.x'
gem 'respond-to'
gem 'rubyzip', '>= 1.3.0'
gem 'sass'
gem 'uglifier', '>= 2.7.2'
gem 'bootstrap-sass', '>= 3.4.0'
gem 'font-awesome-sass'
gem 'webrick', '>= 1.5.1'
