source 'https://rubygems.org'

gem 'coffee-script'
gem 'compass'
gem 'jekyll', '>= 3.0.0'
gem 'jekyll-assets', '>= 1.0.0'
gem 'rake'
gem 'redcarpet', '>= 3.2.3'
gem 'breakpoint', '~> 1.x'
gem 'respond-to'
gem 'rubyzip', '>= 1.2.1'
gem 'sass'
gem 'uglifier', '>= 2.7.2'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'webrick'
